<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="1464" started-at="2017-12-13T17:43:14Z" finished-at="2017-12-13T17:43:15Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="1464" started-at="2017-12-13T17:43:14Z" finished-at="2017-12-13T17:43:15Z">
      <class name="testcase.me.callAndSmsAlarm.TestCase002GetCsAlarmSetList">
        <test-method status="FAIL" signature="testGetCsAlarmSetList()[pri:0, instance:testcase.me.callAndSmsAlarm.TestCase002GetCsAlarmSetList@42bf7a35]" name="testGetCsAlarmSetList" duration-ms="1433" started-at="2017-12-14T01:43:14Z" finished-at="2017-12-14T01:43:15Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[getCsAlarmSetList alarmName错误 expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: getCsAlarmSetList alarmName错误 expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at testcase.me.callAndSmsAlarm.TestCase002GetCsAlarmSetList.testGetCsAlarmSetList(TestCase002GetCsAlarmSetList.java:89)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGetCsAlarmSetList -->
      </class> <!-- testcase.me.callAndSmsAlarm.TestCase002GetCsAlarmSetList -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
